# template_config.toml
[args]
# server model
num_users = 100      # int: number of users: K
all_clients = false   # bool: aggregation over all clients true or false
# server train
epochs = 100          # int: rounds of training
bs = 64             # int: test batch size
frac = 0.30           # float: the fraction of clients: C
gpu = true              # int: gpu device
verbose = false       # bool: verbose print
# client model
model = "lenet"        # str: model name mobilenet, resnet18, lenet
#client train
lr = 0.0067            # float: learning rat
local_ep = 1         # int: the number of local epochs: 2
local_bs = 64        # int: local batch size: 10
momentum = 0.9       # float: SGD momentum (default: 0.5)
weight_decay = 1e-4  # float: SGD weight_decay
# data configuration
dataset = "mnist"    # str: name of dataset cifar10, cifar100 or mnist
iid = "True"           # bool: whether i.i.d or not
# other configuration
seed = 1             # int: random seed (default: 1)
# defense configuration
aggregate_function = "fed_avg" # str: name of defense function layer_defense or fed_avg
# attack configuration
malicious_user_rate = 0.3 # float: malicious user number
toxic_data_ratio = 0.3 # float: Malicious users decide what proportion of their own dataset becomes toxic data
attack_method = "trigger"
epoch_threshold = 50